
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJWGFNWi85SlBhYjB3RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TmpBek1UUXhNVEl6TWpaYUZ3MHpOakF6TVRFeE1USTRNalphTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMrQWNiSzg0b0VFYmttOGRkU1J5Y3VYR3MyS0FxMHhiMlIydGxIRno2VmhXM3hIaXpvTEpEcnJQWkoKVCtmV2ZPTldURk1la1Zhd2RsRERPSkJGdXRsdHJ1ZStKVUhsYzVoOXh6ZjBWZWpCOG41dTkyLzB5OVZQSjJzSwpPWkNXSmxIU2lMLytNN3ZRcCtRbG5kVHJzSjdnT3FiRzdpS2RGU2xEc3FFc1VmelR1SzRRS2llTVNBbGVVYUE1CndKMUhUeEFPb01oWFFXVm9NN0k4a05pRHloL1I1cmFpTFRJaDVxSldhWXVlQ1IrNUVvWXZvQUxKamQzTlNBYVMKa3NhV09FZkZBbXAxUDFhc1J6MVpVVDNXNFVRVVZFMVFIOHkwY0hud2w4cVh0TWJXVzFnNEUyS1pmK0JzQXU2awpaVTh4OFdkWE0rN2NIb2VCYTJUejR5cXE1RXE5QWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJSZm5FQm9wam92YndBOVVzK3lidlpmMEMrdytUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQjBvbTF5WFBKUApqSGRXR29QUnhmbk5yVFF4RHY4VytTR3FNbmhCcGFMRk9qWnZUS3Z6VVF2ZEdrbCtWOUFxK05uelBPbjVjNU02ClB4UE9UQmFSRnpPaDlmTnpVWWp2UHpUL01FL1hIdm12SWlQMHhvRUF6NDNJMHV4azFLL2w0cUxDbXdncW42cmMKTHVDbmY2TCtlY2tubEU4WWFBWXZtanRxWFZPdG9lcVVuNTVucTRuekZZRUZrbHdPZFg1YlZBUks3d0JPeVZkawpqVzlQdm9pMkFLQkwxbHFnMHRTSm5GaDJmLzh5NVRrc0N0Ty9CRWZrVkhCRDZ5RFJmS3BXWlZDWmZ0WGhUL2w1CjVrMVNnaGFtZGc2YmF1YVIvOFgrWVIrbDFIVW1DWUF1SHg5UkpVbDlGSmlGUFJ6ODRvT0ZZUUcxTlFYUERHZW4KelRlcG1uMHdSVzlVCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://F80CD2320D8481E900894443FC95AA80.gr7.ap-south-1.eks.amazonaws.com
  name: arn:aws:eks:ap-south-1:845561723983:cluster/trendstore-cluster
contexts:
- context:
    cluster: arn:aws:eks:ap-south-1:845561723983:cluster/trendstore-cluster
    user: arn:aws:eks:ap-south-1:845561723983:cluster/trendstore-cluster
  name: arn:aws:eks:ap-south-1:845561723983:cluster/trendstore-cluster
current-context: arn:aws:eks:ap-south-1:845561723983:cluster/trendstore-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:ap-south-1:845561723983:cluster/trendstore-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - ap-south-1
      - eks
      - get-token
      - --cluster-name
      - trendstore-cluster
      - --output
      - json
      command: aws
