apiVersion: v1
kind: Service
metadata:
  name: trendstore-service
spec:
  type: LoadBalancer
  selector:
    app: trendstore
  ports:
    - protocol: TCP
      port: 80         # The port users will use (e.g., http://your-elb-url.com)
      targetPort: 3000  # The port where Nginx is listening inside your container
